<?php

namespace App\Utils;



class Clientes
{

    public static function get()
    {

        $name = [
            "Abigail",
            "Abril",
            "Agustina",
            "Alaia",
            "Alana",
            "Alba Luz",
            "Alejandra",
            "Alicia",
            "Alma",
            "Altagracia",
            "Amala",
            "Amalia",
            "Amanda",
            "Ana",
            "Ana Carolina",
            "Ana Lucía",
            "Ana María",
            "Ana Patricia",
            "Ana Sofía",
            "Andrea",
            "Ángeles",
            "Antonella",
            "Antonia",
            "Ariana",
            "Ashley",
            "Bárbara",
            "Beatriz",
            "Belén",
            "Briana",
            "Brithany",
            "Camila",
            "Caridad",
            "Carmen",
            "Carmen Luisa",
            "Carolina",
            "Catalina",
            "Celeste",
            "Claudia",
            "Concepción",
            "Daniela",
            "Danna",
            "Dayana",
            "Del Carmen",
            "Delfina",
            "Domenica",
            "Dulce María",
            "Elizabeth",
            "Emilia",
            "Emily",
            "Emma",
            "Esmeralda",
            "Evelyn",
            "Florencia",
            "Francesca/Francisca",
            "Gabriela",
            "Génesis",
            "Guadalupe",
            "Isabella",
            "Isidora",
            "Jimena",
            "Josefa",
            "Josefina",
            "Juana",
            "Julia",
            "Julieta",
            "Kamila",
            "Karla",
            "Karla Patricia",
            "Kiara",
            "Kimberly",
            "Laura",
            "Leticia",
            "Lidia",
            "Lisandra",
            "Liz",
            "Luana",
            "Lucía",
            "Luciana",
            "Luisa",
            "Luisa Fernanda",
            "Luz",
            "Luz María",
            "Mabel",
            "Maite",
            "Margarita",
            "María",
            "María Ángeles",
            "María Carmen",
            "María Celeste",
            "María del Carmen",
            "María Dolores",
            "María Elena",
            "María Fernanda",
            "María Isabel",
            "María Jesús",
            "María José",
            "María Luisa",
            "María Paula",
            "María Teresa",
            "Mariana",
            "Mariangel",
            "Mariapaz",
            "Maritza",
            "Martha",
            "Martina",
            "Mayelin",
            "Melany",
            "Mercedes",
            "Mia",
            "Mikaela",
            "Morena",
            "Noemí",
            "Odalys",
            "Olga Marina",
            "Olivia",
            "Patricia",
            "Paula",
            "Ramona",
            "Raquel",
            "Reina Isabel",
            "Rosa",
            "Rosmery",
            "Roxana",
            "Salomé",
            "Samantha",
            "Sara Sofía",
            "Sara Valentina",
            "Silvia",
            "Sofía",
            "Sonia",
            "Sophia",
            "Tania",
            "Teresa",
            "Trinidad",
            "Valentina",
            "Valeria",
            "Vanessa",
            "Verónica",
            "Victoria",
            "Ximena",
            "Yadira",
            "Yaima",
            "Yamileth",
            "Yanelis",
            "Yanet",
            "Zoe",
        ];


        $lastname = [
            "GARCIA",
            "RODRIGUEZ",
            "HERNANDEZ",
            "MARTINEZ",
            "LOPEZ",
            "GONZALEZ",
            "PEREZ",
            "SANCHEZ",
            "RAMIREZ",
            "TORRES",
            "FLORES",
            "RIVERA",
            "GOMEZ",
            "DIAZ",
            "CRUZ",
            "MORALES",
            "REYES",
            "GUTIERREZ",
            "ORTIZ",
            "CHAVEZ",
            "RAMOS",
            "RUIZ",
            "MENDOZA",
            "ALVAREZ",
            "JIMENEZ",
            "CASTILLO",
            "VASQUEZ",
            "ROMERO",
            "MORENO",
            "GONZALES",
            "HERRERA",
            "AGUILAR",
            "MEDINA",
            "VARGAS",
            "CASTRO",
            "GUZMAN",
            "MENDEZ",
            "FERNANDEZ",
            "MUNOZ",
            "SALAZAR",
            "GARZA",
            "SOTO",
            "VAZQUEZ",
            "ALVARADO",
            "CONTRERAS",
            "DELGADO",
            "PENA",
            "RIOS",
            "GUERRERO",
            "SANDOVAL",
            "ORTEGA",
            "ESTRADA",
            "NUNEZ",
            "MALDONADO",
            "DOMINGUEZ",
            "VALDEZ",
            "VEGA",
            "SANTIAGO",
            "ESPINOZA",
            "ROJAS",
            "SILVA",
            "MEJIA",
            "MARQUEZ",
            "JUAREZ",
            "PADILLA",
            "LUNA",
            "ACOSTA",
            "FIGUEROA",
            "CORTEZ",
            "AVILA",
            "NAVARRO",
            "MOLINA",
            "AYALA",
            "CAMPOS",
            "SANTOS",
            "CARRILLO",
            "CERVANTES",
            "DURAN",
            "LARA",
            "CABRERA",
            "SOLIS",
            "MIRANDA",
            "ROBLES",
            "FUENTES",
            "SALINAS",
            "VELASQUEZ",
            "OCHOA",
            "AGUIRRE",
            "LEON",
            "CARDENAS",
            "DELEON",
            "RIVAS",
            "CALDERON",
            "ROSALES",
            "SERRANO",
            "CASTANEDA",
            "TRUJILLO",
            "MONTOYA",
            "PACHECO",
            "OROZCO",
            "IBARRA",
            "VALENCIA",
            "GALLEGOS",
            "VELAZQUEZ",
            "CAMACHO",
            "GUERRA",
            "COLON",
            "ESCOBAR",
            "SUAREZ",
            "SALAS",
            "SMITH",
            "MACIAS",
            "VILLARREAL",
            "BARRERA",
            "FRANCO",
            "ZAMORA",
            "DELACRUZ",
            "SANTANA",
            "ROMAN",
            "PINEDA",
            "TREVINO",
            "RANGEL",
            "ARIAS",
            "LOZANO",
            "ZUNIGA",
            "MERCADO",
            "MELENDEZ",
            "MORA",
            "VALENZUELA",
            "ANDRADE",
            "MEZA",
            "VILLANUEVA",
            "GALVAN",
            "TAPIA",
            "ZAVALA",
            "SOSA",
            "VELEZ",
            "CISNEROS",
            "BENITEZ",
            "ACEVEDO",
            "BONILLA",
            "ARROYO",
            "VILLA",
            "RUBIO",
            "BAUTISTA",
            "ARELLANO",
            "JOHNSON",
            "PONCE",
            "HUERTA",
            "BELTRAN",
            "ROCHA",
            "VILLEGAS",
            "CANTU",
            "MONTES",
            "BARAJAS",
            "MATA",
            "MURILLO",
            "ROSAS",
            "CORTES",
            "GUEVARA",
            "SALGADO",
            "ROSARIO",
            "PALACIOS",
            "DAVILA",
            "WILLIAMS",
            "ESPARZA",
            "CUEVAS",
            "CORDOVA",
            "MARTIN",
            "TREJO",
            "QUINTERO",
            "MARIN",
            "BRAVO",
            "CORONA",
            "MEDRANO",
            "NAVA",
            "MAGANA",
            "DEJESUS",
            "BROWN",
            "PORTILLO",
            "VILLALOBOS",
            "ENRIQUEZ",
            "ESQUIVEL",
            "AVALOS",
            "BERNAL",
            "LUGO",
            "DUARTE",
            "CANO",
            "PARRA",
            "ESPINOSA",
            "GALINDO",
            "DELAROSA",
            "QUINTANA",
            "ALFARO",
            "JARAMILLO",
            "LUCERO",
            "CORREA",
            "JONES",
            "REYNA",
            "SIERRA",
            "NIEVES",
            "SALDANA",
            "QUINONES",
            "PERALTA",
            "BECERRA",
            "AMAYA",
            "SAENZ",
            "TOVAR",
            "VERA",
            "LEAL",
            "CARDONA"
        ];


        $id_name = rand(0, count($name));
        $id_lastname = rand(0, count($lastname));

        return strtoupper($name[$id_name] . ' ' .  $lastname[$id_lastname]);
    }
}
